version: '3.8'

services:
  backend:
    build: ./nfse-api
    container_name: desafio_nfse_api
    restart: always
    environment:
       - DB_URL=${DB_URL}
       - DB_USER=${DB_USERNAME}
       - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "8080:8080"

  frontend:
    build: ./nfse-estatico
    container_name: nfse-estatico
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

