services:
  backend:
    build: ./nfse-api
    container_name: desafio_nfse_api
    restart: always
    environment:
       - DB_URL=${DB_URL}
       - DB_USER=${DB_USERNAME}
       - DB_PASSWORD=${DB_PASSWORD} 
       - KAFKA_SERVER=${KAFKA_SERVER} 
       - TOPICO_CREDITO_KAFKA=${TOPICO_CREDITO_KAFKA} 
    ports:
      - "8080:8080"
    depends_on:
      - zookeeper
      - kafka

  frontend:
    build: ./nfse-estatico
    container_name: nfse-estatico
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

  zookeeper:
    container_name: zookeeper-c
    image: confluentinc/cp-zookeeper:latest

    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    container_name: kafka-c
    image: confluentinc/cp-kafka:latest

    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # ESSA IMAGEM É UM DASHBOARD PRA PODER ACOMPANHAR O TOPICO DE MANEIRA MAIS FÁCIL 
  # kafdrop:
  #   container_name: kafdrop
  #   image: obsidiandynamics/kafdrop:latest

  #   depends_on:
  #     - zookeeper
  #     - kafka
  #   ports:
  #     - 19000:9000
  #   environment:
  #     KAFKA_BROKERCONNECT: kafka:29092
